server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: vendor-data-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=vendor;encrypt=true;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:YourStrong!Passw0rd}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
  security:
    oauth2:
      resourceserver:
        jwt:
          # Vendor Auth Server (M2M OAuth2 Authorization Server)
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:9000}
          # or set jwk-set-uri directly: http://localhost:9000/oauth2/jwks
          jwk-set-uri: ${JWT_JWK_SET_URI:}

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.vendor.vendordataservice.api.dto
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
